apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: solar-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        name: solar-nodeclass
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
