apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.mongo.uri }}
  MONGO_USERNAME: {{ .Values.mongo.username }}
  MONGO_PASSWORD: {{ .Values.mongo.password }}
