apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.mongo.uri }}
  MONGO_USERNAME: {{ .Values.mongo.username }}
  MONGO_PASSWORD: {{ .Values.mongo.password }}
env:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongo-secrets
        key: MONGO_URI
  - name: MONGO_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongo-secrets
        key: MONGO_USERNAME
  - name: MONGO_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongo-secrets
        key: MONGO_PASSWORD
