apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ${KARPENTER_NODEPOOL_NAME}
  namespace: ${KARPENTER_NAMESPACE}
spec:
  template:
    spec:
      nodeClassRef:
        name: ${KARPENTER_NODECLASS_NAME}
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ${KARPENTER_NODECLASS_NAME}
  namespace: ${KARPENTER_NAMESPACE}
spec:
  role: ${KARPENTER_NODE_ROLE}
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  instanceProfile: ${KARPENTER_INSTANCE_PROFILE}
