apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "45.7.1"
    helm:
      skipCrds: false
      values: |
        crds:
          enabled: true # Enable CRD installation
        
        # Change all services to ClusterIP instead of LoadBalancer
        prometheus:
          service:
            type: ClusterIP
        
        grafana:
          service:
            type: ClusterIP
          admin:
            existingSecret: grafana-admin-secret
            passwordKey: admin-password
        
        alertmanager:
          service:
            type: ClusterIP
        
        # Enable ingress for all services
        ingress:
          enabled: true
          ingressClassName: nginx  # or your ingress class
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            # Add SSL redirect if you have cert-manager
            # cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: monitoring.yourdomain.com  # Replace with your domain
              paths:
                - path: /prometheus
                  pathType: Prefix
                  backend:
                    service:
                      name: kube-prometheus-stack-prometheus
                      port:
                        number: 9090
                - path: /grafana
                  pathType: Prefix  
                  backend:
                    service:
                      name: kube-prometheus-stack-grafana
                      port:
                        number: 80
                - path: /alertmanager
                  pathType: Prefix
                  backend:
                    service:
                      name: kube-prometheus-stack-alertmanager
                      port:
                        number: 9093
          # Uncomment if using TLS
          # tls:
          #   - secretName: monitoring-tls
          #     hosts:
          #       - monitoring.yourdomain.com

  destination:
    server: https://kubernetes.default.svc
    namespace: ${MONITORING_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true