replicaCount: 1

image:
  repository: ghcr.io/karimzakzouk/graduation-project-devops
  pullPolicy: IfNotPresent
  tag: "7792978f40860101dc685ffd51c0ab12f743e8f6"

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000