replicaCount: 1

image:
  repository: ghcr.io/karimzakzouk/graduation-project-devops
  pullPolicy: IfNotPresent
  tag: "7065525d08b73ee83efbb6fdb0509477a984a778"

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000