replicaCount: 1

image:
  repository: ghcr.io/karimzakzouk/graduation-project-devops
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 443
  
serviceAccount:
  create: false
  name: ""
