name: ArgoCD Deployment
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      cluster_name:
        description: 'EKS Cluster Name'
        required: true
        type: string
      app_namespace:
        description: 'Kubernetes Namespace for the Application'
        required: true
        type: string
      monitoring_namespace:
        description: 'Kubernetes Namespace for Monitoring'
        required: true
        type: string
      argocd_namespace:
        description: 'Kubernetes Namespace for ArgoCD'
        required: true
        type: string
      app_name:
        description: 'Name of the Application'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: false
        default: ''
        type: string
jobs:
  argocd:
    name: ArgoCD & Monitoring Deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region us-east-1

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.0

      - name: Add ArgoCD Helm Repo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Install/Upgrade ArgoCD
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace ${{ inputs.argocd_namespace }} \
            --create-namespace \
            --set server.service.type=LoadBalancer \
            --wait

      - name: Create Application Namespace
        run: |
          kubectl create namespace ${{ inputs.app_namespace }} --dry-run=client -o yaml | kubectl apply -f -