name: Kubernetes Deployment
on:
  workflow_dispatch:
  workflow_call:
jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region us-east-1
          
      - name: Create Application Namespace
        run: |
          kubectl create namespace ${{ vars.APP_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ vars.APP_NAME }} ./helm \
            --namespace ${{ vars.APP_NAMESPACE }} \
            --set mongo.uri="${{ secrets.MONGO_URI }}" \
            --set mongo.username="${{ secrets.MONGO_USERNAME }}" \
            --set mongo.password="${{ secrets.MONGO_PASSWORD }}" \
            --set image.tag="${{ inputs.image-tag || github.sha }}"
            
      - name: Deploy ArgoCD Applications
        run: |
          export APP_NAME=${{ vars.APP_NAME }}
          export APP_NAMESPACE=${{ vars.APP_NAMESPACE }}
          export ARGOCD_NAMESPACE=${{ vars.ARGOCD_NAMESPACE }}
          envsubst < ./argocd/application.yml | kubectl apply -f -
            