name: Kubernetes Deployment

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag to deploy'
        required: false
        default: 'latest'
        type: string
  workflow_call:
    inputs:
      image-tag:
        description: 'Docker image tag to deploy'
        required: false
        default: 'latest'
        type: string

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write  # Allow writing to repository
      actions: read
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name otel-cluster --region us-east-1 

      - name: Configure kubectl
        uses: statsig-io/kubectl-via-eksctl@main
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          cluster: otel-cluster


      - name: Create Base64-encoded K8s Secret
        run: |
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: mongo-secrets
          type: Opaque
          data:
            MONGO_URI: $(echo -n "${{ secrets.MONGO_URI }}" | base64)
            MONGO_USERNAME: $(echo -n "${{ secrets.MONGO_USERNAME }}" | base64)
            MONGO_PASSWORD: $(echo -n "${{ secrets.MONGO_PASSWORD }}" | base64)
          EOF

      - name: Update Helm values with new image tag
        run: |
          IMAGE_TAG=${{ inputs.image-tag || github.sha }}
          # Update the image tag in values.yaml for ArgoCD to pick up
          sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|g" ./helm/values.yaml
          
      - name: Commit updated image tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/values.yaml
          git commit -m "Update image tag to ${{ inputs.image-tag || github.sha }}" || exit 0
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Create Application Namespace
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          kubectl create namespace my-app-namespace --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy ArgoCD Applications
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          kubectl apply -f ./argocd/application.yml
          
      - name: Print Service Endpoints
        run: |
          echo "================= SERVICE ENDPOINTS ================="
          echo "ArgoCD:     http://$(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
          echo "Prometheus: http://$(kubectl get svc kube-prometheus-stack-prometheus -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'):9090"
          echo "Grafana:    http://$(kubectl get svc kube-prometheus-stack-grafana -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
          echo "App:        http://$(kubectl get svc my-app-svc -n my-app-namespace -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"

          echo "================= DEFAULT CREDENTIALS ================="
          echo "ArgoCD -> Username: admin"
          echo "ArgoCD -> Password: $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)"
          echo "Grafana -> Username: admin"
          echo "Grafana -> Password: $(kubectl get secret kube-prometheus-stack-grafana -n monitoring -o jsonpath='{.data.admin-password}' | base64 -d)"
          echo "Prometheus -> No login needed (anonymous access by default)"
