name: Kubernetes Deployment
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      cluster_name:
        description: 'EKS Cluster Name'
        required: true
        type: string
      app_namespace:
        description: 'Kubernetes Namespace for the Application'
        required: true
        type: string
      monitoring_namespace:
        description: 'Kubernetes Namespace for Monitoring'
        required: true
        type: string
      argocd_namespace:
        description: 'Kubernetes Namespace for ArgoCD'
        required: true
        type: string
      app_name:
        description: 'Name of the Application'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: false
        default: ''
        type: string
jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region us-east-1

      - name: Create Application Namespace
        run: |
          kubectl create namespace ${{ inputs.app_namespace }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Secrets
        run: |
          kubectl create secret generic mongo-secrets \
            --from-literal=MONGO_URI="${{ secrets.MONGO_URI }}" \
            --from-literal=MONGO_USERNAME="${{ secrets.MONGO_USERNAME }}" \
            --from-literal=MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            -n ${{ inputs.app_namespace }} --dry-run=client -o yaml | kubectl apply -f -



      - name: Deploy ArgoCD Applications
        run: |
          export APP_NAME=${{ inputs.app_name }}
          export APP_NAMESPACE=${{ inputs.app_namespace }}
          export ARGOCD_NAMESPACE=${{ inputs.argocd_namespace }}
          envsubst < ./argocd/application.yml | kubectl apply -f -
            