name: Print Service Endpoints
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      cluster_name:
        description: 'EKS Cluster Name'
        required: true
        type: string
      app_namespace:
        description: 'Kubernetes Namespace for the Application'
        required: true
        type: string
      monitoring_namespace:
        description: 'Kubernetes Namespace for Monitoring'
        required: true
        type: string
      argocd_namespace:
        description: 'Kubernetes Namespace for ArgoCD'
        required: true
        type: string
      app_name:
        description: 'Name of the Application'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: false
        default: ''
        type: string

jobs:
  print-endpoints:
    name: Print Service Endpoints
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region us-east-1

      - name: Print Service Endpoints
        run: |
          echo "================= SERVICE ENDPOINTS ================="
          ARGOCD_HOST=$(kubectl get svc argocd-server -n ${{ inputs.argocd_namespace }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo 'Not found')
          PROM_HOST=$(kubectl get svc kube-prometheus-stack-prometheus -n ${{ inputs.monitoring_namespace }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo 'Not found')
          GRAFANA_HOST=$(kubectl get svc kube-prometheus-stack-grafana -n ${{ inputs.monitoring_namespace }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo 'Not found')
          APP_HOST=$(kubectl get svc ${{ inputs.app_name }}-svc -n ${{ inputs.app_namespace }} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo 'Not found')
          echo "ArgoCD: http://$ARGOCD_HOST"
          echo "Prometheus: http://$PROM_HOST:9090"
          echo "Grafana: http://$GRAFANA_HOST"
          echo "App: http://$APP_HOST"
          echo "================= DEFAULT CREDENTIALS ================="
          ARGOCD_PASS=$(kubectl -n ${{ inputs.argocd_namespace }} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' 2>/dev/null | base64 -d || echo 'Not found')
          echo "ArgoCD -> Username: admin"
          echo "ArgoCD -> Password: $ARGOCD_PASS"
          echo "Grafana -> Username: admin"
          echo "Grafana -> Password: ${{ secrets.GRAFANA_PASSWORD }}"
          echo "Prometheus -> No login needed (anonymous access by default)"