name: Monitoring Deployment
on:
  workflow_dispatch:

jobs:
  monitoring:
    name: Deploy Monitoring Stack
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region us-east-1

      - name: Create Grafana Secret
        run: |
          kubectl create namespace ${{ vars.MONITORING_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic grafana-admin-secret \
            --from-literal=admin-user=admin \
            --from-literal=admin-password='${{ secrets.GRAFANA_ADMIN_PASSWORD }}' \
            --namespace ${{ vars.MONITORING_NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Monitoring
        run: |
          export MONITORING_NAMESPACE=${{ vars.MONITORING_NAMESPACE }}
          export ARGOCD_NAMESPACE=${{ vars.ARGOCD_NAMESPACE }}
          envsubst < ./argocd/monitoring.yml | kubectl apply -f -
