name: Terraform Infrastructure
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      terraform-action:
        description: 'Terraform action to perform (plan/apply/destroy)'
        required: false
        default: 'apply'
        type: string
    outputs:
      terraform-result:
        description: "Terraform execution result"
        value: ${{ jobs.terraform.outputs.result }}
jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    environment: production
    outputs:
      result: ${{ steps.terraform-apply.outcome }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Terraform
      - name: Terraform Apply
        id: terraform-apply
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: terraform apply -auto-approve
        working-directory: ./Terraform

      # ---------------------------
      # Install ArgoCD with Helm
      # ---------------------------
      - name: Update kubeconfig
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          aws eks update-kubeconfig --name otel-cluster --region us-east-1
      - name: Install Helm
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.0
      - name: Add ArgoCD Helm Repo
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
      - name: Install/Upgrade ArgoCD
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --set server.service.type=LoadBalancer \
            --wait

      - name: Create Grafana Secret
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic grafana-admin-secret \
            --from-literal=admin-user=admin \
            --from-literal=admin-password='${{ secrets.GRAFANA_ADMIN_PASSWORD }}' \
            --namespace monitoring \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Monitoring
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          kubectl apply -f ./argocd/monitoring.yml

      # ---------------------------
      # Print Access URLs & Credentials
      # ---------------------------
      - name: Get ArgoCD URL
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          echo "Waiting for ArgoCD LoadBalancer..."
          kubectl wait --namespace argocd \
            --for=condition=available svc/argocd-server \
            --timeout=300s

          ARGOCD_URL=$(kubectl get svc argocd-server -n argocd \
            -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          echo "ArgoCD URL: $ARGOCD_URL"
          echo "ArgoCD Username: admin"
          echo "ArgoCD Password:"
          kubectl -n argocd get secret argocd-initial-admin-secret \
            -o jsonpath="{.data.password}" | base64 --decode
          echo ""

      - name: Get Prometheus URL
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          echo "Waiting for Prometheus LoadBalancer..."
          kubectl wait --namespace monitoring \
            --for=condition=available svc/kube-prometheus-stack-prometheus \
            --timeout=300s

          PROM_URL=$(kubectl get svc kube-prometheus-stack-prometheus -n monitoring \
            -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          echo "Prometheus URL: $PROM_URL"
          echo ""

      - name: Get Grafana URL
        if: ${{ inputs.terraform-action == 'apply' || inputs.terraform-action == '' }}
        run: |
          echo "Waiting for Grafana LoadBalancer..."
          kubectl wait --namespace monitoring \
            --for=condition=available svc/kube-prometheus-stack-grafana \
            --timeout=300s

          GRAFANA_URL=$(kubectl get svc kube-prometheus-stack-grafana -n monitoring \
            -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          echo "Grafana URL: $GRAFANA_URL"
          echo "Grafana Username: admin"
          echo "Grafana Password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}"
          echo ""